### ISSUE TITLE
Cadet JoseKus

### ISSUE THREAD

**Issue by DevElCuy** [devcoin/shares#1]
Recently JoseKus joined the Telegram group to reach out and offer hosting for devcoin.org which is currently maintained by me. He is a hosting provider and has way better infrastructure than we can afford.

For the reasons above I'm accepting the offer and recruiting JoseKus as Cadet for the Devcoin A-Team

**Comment by almajosecarlos** [comment]
Hello!, glad to be part of DevCoin as a Cadet :D.  I accept the proposal.

I'm happy to bring my hosting services to this endevour!.

**Comment by Satoshi0x** [comment]
Welcome welcome always loving those who find the value in our project! :)

-Dan (A-Team)

**Comment by almajosecarlos** [comment]
Thanks! so. What are we guys up to  this month :D?

**Comment by DevElCuy** [comment]
@almajosecarlos can you confirm your Devcoin address over here? I'm assigning you 1/5 of a Devcoin Share for hosting the website

**Comment by Satoshi0x** [comment]
Changing the way people think they know history by helping everyone 

Daniel R. Treccia
***@***.***
keybase.io/satoshi0x

**Comment by almajosecarlos** [comment]
@develCuy  here it is: 1Je1KB6sT1DzKtFwTG4xuD2Cd87uZ2wAsA

Thanks :D

**Comment by DevElCuy** [comment]
@almajosecarlos, you will start getting coins from round 127 (starting at block 508,000)
