### ISSUE TITLE
Business Developer

### ISSUE THREAD

**Issue by DevElCuy** [devcoin/shares#2]
@Satoshi0x has contributed key connections to the project this year, going beyond his current Marketing duty. We are now collaborating with Unobtanium, UNOparty and COYE communities thanks to Satoshis0x's help.

For the reasons above I delegate Community Management role to Satoshi0x and transferring him 1/5 of a Devcoin Share I have for Ongoing Factotum duty, also giving an end to such role. Earning Factotum duty will absorb Ongoing Factotum responsibility from now on.

**Comment by Satoshi0x** [comment]
Thank you Fernando. :)

Could you please change my shares payout address to the following for future rounds?

1AaC6ouxVPkkc8pahhni99PiUuTVr6o7tk

This will go to my 22.x wallet as I cannot import my old address from 0.8.9.x using importprivkey :)

Gracias.

**Comment by DevElCuy** [comment]
@Satoshi0x is now Business Developer since he is better suited for that role. I'm taking over Community Management while I find someone else for delegation.
